spring:
  datasource:
    url: ${cws.datasource.url}
    username: ${cws.datasource.username}
    password: ${cws.datasource.password}
    hikari:
      schema: ${cws.datasource.schema}
  flyway:
    enabled: true # enables flyway database migration
    locations: classpath:db/migration # migration scripts location
    validate-on-migrate: true
    default-schema: ${cws.datasource.schema}