server:
  port: ${cws.sync.port.exposed}
  servlet:
    contextPath: /cws-sync
spring:
  application:
    name: web-software-engineer-task-sync
  datasource:
    url: ${cws.datasource.url}
    username: ${cws.datasource.username}
    password: ${cws.datasource.password}
  jpa:
    open-in-view: false
  main:
    allow-bean-definition-overriding: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  task:
    execution:
      pool:
        core-size: 20
        max-size: 20
        queue-capacity: 20
cws:
  github:
    api:
      base:
        url: ${cws.github.api.base.url}
      authorization:
        token: ${cws.github.api.authorization.token}
    sync:
      scheduled:
        rate: ${cws.github.sync.scheduled.rate}
    user:
      page:
        size: ${cws.github.user.page.size}
      count:
        max: ${cws.github.user.count.max}
  security:
    jwt:
      secret: ${cws.security.jwt.secret}
      expiration:
        ms: ${cws.security.jwt.expiration.ms}
    refresh:
      token:
        expiration:
          ms: ${cws.security.refresh.token.expiration.ms}