server:
  servlet:
    contextPath: /cws-sync
spring:
  application:
    name: web-software-engineer-task-sync
  datasource:
    url: ${cws.datasource.url}
    username: ${cws.datasource.username}
    password: ${cws.datasource.password}
  jpa:
    open-in-view: false
  main:
    allow-bean-definition-overriding: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
cws:
  github:
    authorization:
      token: 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
    sync:
      scheduled:
        rate: ${cws.github.sync.scheduled.rate}
    user:
      page:
        size: ${cws.github.user.page.size}
      count:
        max: ${cws.github.user.count.max}