spring:
  application:
    name: web-software-engineer-task-backend
  datasource:
    url: ${cws.datasource.url}
    username: ${cws.datasource.username}
    password: ${cws.datasource.password}
  jpa:
    open-in-view: false