version: "2.4"
services:
  frontend_service:
    image: ${CWS_FRONTEND_IMAGE_NAME}
    container_name: ${CWS_FRONTEND_CONTAINER_NAME}
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${CWS_FRONTEND_PORT}:3000
    env_file:
      - .env