version: "2.4"
services:
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: mysqladmin -h 127.0.0.1 ping -P 3306 -p${MYSQL_ROOT_PASSWORD}|grep 'mysqld is alive'
      interval: 10s
      timeout: 30s
      retries: 5
    networks:
      - springapimysql-net

  database_service:
    image: "cws/web-software-engineer-task-database:0.0.1"
    restart: on-failure
    networks:
      - springapimysql-net 
    depends_on:
      mysqldb:
        condition: service_healthy

  backend_service:
    image: "cws/web-software-engineer-task-backend:0.0.1"
    restart: always
    ports:
      - ${CWS_BACKEND_PORT}:8080
    volumes:
      - ${CWS_LOG_BASEDIR}:${CWS_LOG_BASEDIR}
    networks:
      - springapimysql-net 
    depends_on:
      mysqldb:
        condition: service_healthy
      database_service:
        condition: service_started
      
  sync_service:
    image: "cws/web-software-engineer-task-sync:0.0.1"
    restart: always
    ports:
      - ${CWS_SYNC_PORT}:8080
    volumes:
      - ${CWS_LOG_BASEDIR}:${CWS_LOG_BASEDIR}
    networks:
      - springapimysql-net
    depends_on:
      mysqldb:
        condition: service_healthy
      backend_service:
        condition: service_started
      database_service:
        condition: service_started

networks:
  springapimysql-net:
    driver: bridge