version: "2.4"
services:
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - springapimysql-net

  database_service:
    image: "cws/web-software-engineer-task-database:0.0.1"
    restart: on-failure
    networks:
      - springapimysql-net 
    depends_on:
      mysqldb:
        condition: service_started

  backend_service:
    image: "cws/web-software-engineer-task-backend:0.0.1"
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net 
    depends_on:
      mysqldb:
        condition: service_started
      database_service:
        condition: service_started
      
  sync_service:
    image: "cws/web-software-engineer-task-sync:0.0.1"
    restart: always
    ports:
      - 8090:8090
    networks:
      - springapimysql-net
    depends_on:
      mysqldb:
        condition: service_started
      database_service:
        condition: service_started

networks:
  springapimysql-net:
    driver: bridge